<?php
$enabled = $block->isEnabled();
$form_action = $block->formAction();
?>

<?php if ($enabled): ?>
    <style type="text/css">
        .psq-add-card {
            display: block;
            margin-top: 8px;

        }

        .psq-add-card__form--hidden {
            visibility: hidden;
        }

        .psq-add-card__form {
            display: block;
            padding: 4px;
        }

        .psq-form__section {
            display: block;
            margin: 4px;
        }

        .psq-form__input {
            margin: 4px;
            display: inline-block;
        }

    </style>
    <div class="psq-add-card">
        <button id="psq-cc-add-button" class="psq__cc-add-btn--enabled">Add Card</button>

        <div class="psq-add-card__form psq-add-card__form--hidden psq-form">
            <p class="psq-form__cta">Enter new card information</p>
            <div class="psq-form__section">
                <label for="psq-form-cardholder-name">Cardholder Name</label>
                <input id="psq-form-cardholder-name"
                       class="psq-form__input"
                       type="text"
                       name="cardholder_name"
                       value="<?php echo $escaper->escapeHtml($block->getCustomerName()); ?>"/>

            </div>
            <div class="psq-form__section">
                <div id="psq-card-element"></div>

            </div>
            <div class="psq-form__actions">
                <button class="psq-form__button psq-form__button--primary action primary"
                        type="submit">
                    <span>Add Payment Method</span>
                </button>
                <button class="psq-form__button psq-form__button--cancel action"
                        type="button">
                    <span>Cancel</span>
                </button>
            </div>
            <form id="psq-save-to-vault" action="<?php echo $form_action; ?>" method="post">
                <input id="psq-new-card-id" type="hidden" name="card_id"/>
                <input id="psq-new-card-exp-year" name="exp_year" type="hidden"/>
                <input id="psq-new-card-exp-month" name="exp_month" type="hidden"/>
                <input id="psq-new-card-details" name="details" type="hidden"/>

            </form>
        </div>
    </div>
    <script type="text/x-magento-init">
        <?= /* @noEscape */ json_encode([
            '*' => [
                'PublicSquare_Payments/js/add-card' => [
                    'publicKey' => $block->getPublicKey(),
                    'cardInputCustomization' => $block->getCardInputCustomizationJSON(),
                ],
            ],
        ], JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT) ?>
    </script>
<?php endif; ?>
